export const db = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID || "main-stackoverflow"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID || "question-attachment"